const AllData = 

[
    {
        "id": 1,
        "place": "Basundhara R/A, Dhaka",
        "size": 1200,
        "bedroom": 3,
        "bathroom": 2,
        "image": "image1.jpg",
        "type": "Normal Apartment in Basundhara",
        "condition": null,
    },
    {
        "id": 2,
        "place": "Uttara R/A, Dhaka",
        "size": 1500,
        "bedroom": 4,
        "bathroom": 3,
        "image": "image2.jpg",
        "type": "Luxury Condominium Apartment in Uttara",
        "condition": null,
    },
    {
        "id": 3,
        "place": "Savar",
        "size": 1000,
        "bedroom": 2,
        "bathroom": 1,
        "image": "image3.jpg",
        "type": "Normal Apartment in Savar",
        "condition": null,
    },
    {
        "id": 4,
        "place": "Nabinagar",
        "size": 900,
        "bedroom": 2,
        "bathroom": 1,
        "image": "image4.jpg",
        "type": "Normal Apartment in Nabinagar",
        "condition": null,
    },
    {
        "id": 5,
        "place": "Dhanmandi R/A, Dhaka",
        "size": 1600,
        "bedroom": 3,
        "bathroom": 3,
        "image": "image5.jpg",
        "type": "Expensive Apartment in Dhanmandi",
        "condition": "urgent"
    },
    {
        "id": 6,
        "place": "Banani R/A, Dhaka",
        "size": 1300,
        "bedroom": 3,
        "bathroom": 2,
        "image": "image6.jpg",
        "type": "Normal Apartment in Banani",
        "condition": null,
    },
    {
        "id": 7,
        "place": "Gulshan R/A, Dhaka",
        "size": 1800,
        "bedroom": 4,
        "bathroom": 3,
        "image": "image7.jpg",
        "type": "Luxury Condominium Apartment in Gulshan",
        "condition": "urgent"
    },
    {
        "id": 8,
        "place": "Dhanmandi R/A, Dhaka",
        "size": 1100,
        "bedroom": 2,
        "bathroom": 2,
        "image": "image8.jpg",
        "type": "Normal Apartment in Dhaka",
        "condition": null,
    },
    {
        "id": 9,
        "place": "Basundhara R/A, Dhaka",
        "size": 1400,
        "bedroom": 3,
        "bathroom": 3,
        "image": "image9.jpg",
        "type": "Expensive Apartment in Basundhara",
        "condition": null,
    },
    {
        "id": 10,
        "place": "Uttara R/A, Dhaka",
        "size": 1200,
        "bedroom": 3,
        "bathroom": 2,
        "image": "image10.jpg",
        "type": "Normal Apartment in Uttara",
        "condition": null
    },
    {
        "id": 11,
        "place": "Savar",
        "size": 950,
        "bedroom": 2,
        "bathroom": 1,
        "image": "image11.jpg",
        "type": "Normal Apartment in Savar",
        "condition": null
    },
    {
        "id": 12,
        "place": "Nabinagar",
        "size": 1050,
        "bedroom": 2,
        "bathroom": 2,
        "image": "image12.jpg",
        "type": "Normal Apartment in Nabinagar",
        "condition": "regular"
    },
    {
        "id": 13,
        "place": "Dhanmandi R/A, Dhaka",
        "size": 1700,
        "bedroom": 4,
        "bathroom": 3,
        "image": "image13.jpg",
        "type": "Luxury Condominium Apartment in Dhanmandi",
        "condition": "urgent"
    },
    {
        "id": 14,
        "place": "Banani R/A, Dhaka",
        "size": 1500,
        "bedroom": 3,
        "bathroom": 3,
        "image": "image14.jpg",
        "type": "Expensive Apartment in Banani",
        "condition": null,
    },
    {
        "id": 15,
        "place": "Gulshan R/A, Dhaka",
        "size": 2000,
        "bedroom": 5,
        "bathroom": 4,
        "image": "image15.jpg",
        "type": "Luxury Condominium Apartment in Gulshan",
        "condition": "urgent"
    },
    {
        "id": 16,
        "place": "Gulshan R/A, Dhaka",
        "size": 1100,
        "bedroom": 2,
        "bathroom": 2,
        "image": "image16.jpg",
        "type": "Normal Apartment in Dhaka",
        "condition": null
    },
    {
        "id": 17,
        "place": "Basundhara R/A, Dhaka",
        "size": 1300,
        "bedroom": 3,
        "bathroom": 2,
        "image": "image17.jpg",
        "type": "Normal Apartment in Basundhara",
        "condition": null
    },
    {
        "id": 18,
        "place": "Uttara R/A, Dhaka",
        "size": 1600,
        "bedroom": 4,
        "bathroom": 3,
        "image": "image18.jpg",
        "type": "Luxury Condominium Apartment in Uttara",
        "condition": "urgent"
    },
    {
        "id": 19,
        "place": "Savar",
        "size": 1000,
        "bedroom": 2,
        "bathroom": 1,
        "image": "image19.jpg",
        "type": "Normal Apartment in Savar",
        "condition": null,
    },
    {
        "id": 20,
        "place": "Nabinagar",
        "size": 950,
        "bedroom": 2,
        "bathroom": 1,
        "image": "image20.jpg",
        "type": "Normal Apartment in Nabinagar",
        "condition": null,
    },
    {
        "id": 21,
        "place": "Dhanmandi R/A, Dhaka",
        "size": 1750,
        "bedroom": 4,
        "bathroom": 3,
        "image": "image21.jpg",
        "type": "Luxury Condominium Apartment in Dhanmandi",
        "condition": null,
    },
    {
        "id": 22,
        "place": "Banani R/A, Dhaka",
        "size": 1400,
        "bedroom": 3,
        "bathroom": 2,
        "image": "image22.jpg",
        "type": "Expensive Apartment in Banani",
        "condition": null,
    },
    {
        "id": 23,
        "place": "Gulshan R/A, Dhaka",
        "size": 1900,
        "bedroom": 4,
        "bathroom": 3,
        "image": "image23.jpg",
        "type": "Luxury Condominium Apartment in Gulshan",
        "condition": "urgent"
    },
    {
        "id": 24,
        "place": "Dhanmandi R/A, Dhaka",
        "size": 1200,
        "bedroom": 3,
        "bathroom": 2,
        "image": "image24.jpg",
        "type": "Normal Apartment in Dhaka",
        "condition": null,
    },
    {
            "id": 25,
            "place": "Basundhara R/A, Dhaka",
            "size": 1250,
            "bedroom": 3,
            "bathroom": 2,
            "image": "image25.jpg",
            "type": "Normal Apartment in Basundhara",
            "condition": null
        },
        {
            "id": 26,
            "place": "Uttara R/A, Dhaka",
            "size": 1550,
            "bedroom": 4,
            "bathroom": 3,
            "image": "image26.jpg",
            "type": "Luxury Condominium Apartment in Uttara",
            "condition": "urgent"
        },
        {
            "id": 27,
            "place": "Savar",
            "size": 1020,
            "bedroom": 2,
            "bathroom": 1,
            "image": "image27.jpg",
            "type": "Normal Apartment in Savar",
            "condition": null
        },
        {
            "id": 28,
            "place": "Nabinagar",
            "size": 920,
            "bedroom": 2,
            "bathroom": 1,
            "image": "image28.jpg",
            "type": "Normal Apartment in Nabinagar",
            "condition": null
        },
        {
            "id": 29,
            "place": "Dhanmandi R/A, Dhaka",
            "size": 1650,
            "bedroom": 3,
            "bathroom": 3,
            "image": "image29.jpg",
            "type": "Expensive Apartment in Dhanmandi",
            "condition": "urgent"
        },
        {
            "id": 30,
            "place": "Banani R/A, Dhaka",
            "size": 1350,
            "bedroom": 3,
            "bathroom": 2,
            "image": "image30.jpg",
            "type": "Normal Apartment in Banani",
            "condition": null
        },
        {
            "id": 31,
            "place": "Gulshan R/A, Dhaka",
            "size": 1820,
            "bedroom": 4,
            "bathroom": 3,
            "image": "image31.jpg",
            "type": "Luxury Condominium Apartment in Gulshan",
            "condition": "urgent"
        },
        {
            "id": 32,
            "place": "Uttara R/A, Dhaka",
            "size": 1150,
            "bedroom": 2,
            "bathroom": 2,
            "image": "image32.jpg",
            "type": "Normal Apartment in Dhaka",
            "condition": null
        },
        {
            "id": 33,
            "place": "Basundhara R/A, Dhaka",
            "size": 1450,
            "bedroom": 3,
            "bathroom": 3,
            "image": "image33.jpg",
            "type": "Expensive Apartment in Basundhara",
            "condition": null
        },
        {
            "id": 34,
            "place": "Uttara R/A, Dhaka",
            "size": 1250,
            "bedroom": 3,
            "bathroom": 2,
            "image": "image34.jpg",
            "type": "Normal Apartment in Uttara",
            "condition": null
        },
        {
            "id": 35,
            "place": "Savar",
            "size": 980,
            "bedroom": 2,
            "bathroom": 1,
            "image": "image35.jpg",
            "type": "Normal Apartment in Savar",
            "condition": null
        },
        {
            "id": 36,
            "place": "Nabinagar",
            "size": 1000,
            "bedroom": 2,
            "bathroom": 2,
            "image": "image36.jpg",
            "type": "Normal Apartment in Nabinagar",
            "condition": null
        },
        {
            "id": 37,
            "place": "Dhanmandi R/A, Dhaka",
            "size": 1750,
            "bedroom": 4,
            "bathroom": 3,
            "image": "image37.jpg",
            "type": "Luxury Condominium Apartment in Dhanmandi",
            "condition": "urgent"
        },
        {
            "id": 38,
            "place": "Banani R/A, Dhaka",
            "size": 1520,
            "bedroom": 3,
            "bathroom": 3,
            "image": "image38.jpg",
            "type": "Expensive Apartment in Banani",
            "condition": null
        },
        {
            "id": 39,
            "place": "Gulshan R/A, Dhaka",
            "size": 2010,
            "bedroom": 5,
            "bathroom": 4,
            "image": "image39.jpg",
            "type": "Luxury Condominium Apartment in Gulshan",
            "condition": "urgent"
        },
        {
            "id": 40,
            "place": "Banani R/A, Dhaka",
            "size": 1120,
            "bedroom": 2,
            "bathroom": 2,
            "image": "image40.jpg",
            "type": "Normal Apartment in Dhaka",
            "condition": null
        },
        {
            "id": 41,
            "place": "Basundhara R/A, Dhaka",
            "size": 1320,
            "bedroom": 3,
            "bathroom": 2,
            "image": "image41.jpg",
            "type": "Normal Apartment in Basundhara",
            "condition": "regular"
        },
        {
            "id": 42,
            "place": "Uttara R/A, Dhaka",
            "size": 1620,
            "bedroom": 4,
            "bathroom": 3,
            "image": "image42.jpg",
            "type": "Luxury Condominium Apartment in Uttara",
            "condition": "urgent"
        },
        {
            "id": 43,
            "place": "Savar",
            "size": 1010,
            "bedroom": 2,
            "bathroom": 1,
            "image": "image43.jpg",
            "type": "Normal Apartment in Savar",
            "condition": null
        },
        {
            "id": 44,
            "place": "Nabinagar",
            "size": 960,
            "bedroom": 2,
            "bathroom": 1,
            "image": "image44.jpg",
            "type": "Normal Apartment in Nabinagar",
            "condition": null
        }
    
    
]
export default AllData